
const blog = {
    title: '2024-09-01 - new_yob.md',
    content: `
        Two months since my last post, woops. Well lot's to catch up on then, so settle in for a lengthy read. I want to cover 4 things; 75 hard, a retro on my last job, because I found a new one!, and my next moves.

        So we completed "75 Hard". It was tough, and we bent the rules a tiny bit, but we (my wife and I) really killed it, I do have to say. There may have been a couple walks counted as exercise, but will all of the other criteria we were perfect. It feels really good to complete and I have started again though a shorter block. We're not doing the follow up phases which seem the same but with "do 3 other tasks of your choosing", so kind of a let down in terms of like behavior change. The biggest win from 75 Hard was losing 10 pounds. I didn't really need to but it feels good to achieve that considering I had been mildly trying to get back to that college weight for a couple years. In the same vein, it's really helped me look at sugar in a different way, I now walk down the street and see watch so many people just dumping sugar into their bodies, it's a little crazy once you look at it this way. I will say that the personal development reading was a big help with the job search; I was a pretty consistent person already but this helped me put in that little bit extra time. And last thing is that you have to beware of the drop off at the end; we always intended to keep going after but with a mini break, but that break turned out much longer than expected.

        Now I want to look back at my time at Galvanize/Hack Reactor. I really enjoyed the mission, the culture, and the tasks weren't half bad. A year of teaching was rewarding and educational but ultimately not the ideal type of work for me. I'm just not that comfortable in front of a crowd still; and I still hope to be one day but I'll have to keep pushing in another way. Then on to a year as a curriculum writer. This brought its own new challenges, mainly learning about the format, prose, and design of content writing. This too was rewarding work, as our curriculum needed some refreshing and instructors regularly appreciated it, but I didn't find myself out of the comfort zone technically.

        The job search is finally over! I nearly shed a tear when I got my new job offer. I already had 1 offer but I was hoping for more and when the second one came in and I learned that my salary wouldn't be dropping but increasing significantly, it made pushing for the entire summer worth it. I racked up 303.5 hours of job searching in 6.5 months. That's 61, 41, 36, 29.5, 44.5, 55, and 36.5 hours in each month respectively from Feb to half way through Aug. Which averages to almost 11 hours per week for 28 weeks. Averaging 10 hours per week, now that I've done the match, feels low. I went to cafes on the weekends, did 75 Hard in the middle of this, and released 1.5 new products at work during this time; all this to say that I was burnt out at the end of it. Hence the relief and the overdoing-it after 75 Hard. When you boil it down, I probably spent half my time on algos and system design and the other half on networking. So I did not track my applications (I'd guess single digit cold applies) or outreaches but rather my time.

        The new position will be a Senior Frontend Engineer role at a large but still growing fintech. I'm super excited to work on production quality and greenfield products again. Not to mention getting a senior title, a big tech company on my resume, and the fact that they have an optional-ish office 30 minutes away.

        My plans going forward are first and foremost to excel at the new gig, even if that means weekend hours; to represent myself well for performance trajectory but also to have a strong reputation in case of RIFs. Recently hired employees are at risk. Now that I've relaxed for too long I also am going to attempt to run a marathon. So I'm doing a decently tough training schedule and sort of following a 75 Hard structure (wow, how many times is he going to reference this damn training?). Beyond that I'll get back on the AWS solutions architect track, having pushed my test date out to allow for work onboarding time. And TODAY I'm brainracking (chiller, longer session, less collaborative brainstorming) for my startup's product. My plan is to incorporate (or whatever) a consulting company and start building mission driven products as my trial/testimonial/portfolio suite.

        Let's see if it actually happens. It will! (I hope)
    `,
};

export default blog;
